se_consultants/homepage/urls.py
from django.urls import path

# from homepage import views
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('message_sent/', views.message_sent, name='message_sent'),
    path('about/', views.about, name='about'),
    path('services/', views.services, name='services'),
]

se_consultants/projects/urls.py
from django.urls import path

from . import views

app_name = 'projects'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='details'),
]

se_consultants/se_consultants/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('homepage.urls')),
    # path('homepage/', include('homepage.urls')),
    path('projects/', include('projects.urls')),
    path('admin/', admin.site.urls),
]

se_consultants/homepage/models.py
from django.db import models

# Create your models here.
class Contacts(models.Model):
    name = models.CharField(max_length=30)
    email = models.EmailField()
    contact_no = models.IntegerField(default=0)
    message = models.TextField()

se_consultants/projects/models.py
from django.db import models

# Create your models here.
class Projects(models.Model):
    project_name = models.CharField(max_length=200)
    client = models.CharField(max_length=200)
    work_type = models.CharField(max_length=200)
    completion_status = models.CharField(max_length=10)
    project_banner = models.FilePathField(path='/images')
    project_description = models.CharField(max_length=1000)

    def __str__(self):
        return self.project_name

se_consultants/homepage/forms.py
from django import forms

class ContactForm(forms.Form):
    name = forms.CharField(max_length=30, required=True)
    from_email = forms.EmailField(required=True)
    phone_number = forms.CharField(max_length=20)
    subject = forms.CharField(max_length=100, required=True)
    message = forms.CharField(widget=forms.Textarea, required=True)
    # we can also add captcha here. But not at the moment.
    def __init__(self, *args, **kwargs):
        super(ContactForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'

se_consultants/homepage/views.py
from django.shortcuts import render
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse
from django.shortcuts import render, redirect

from .forms import ContactForm

# Create your views here.
def index(request):
    return render(request, 'homepage/index.html')

def message_sent(request):
    return render(request, 'homepage/message_sent.html')

def about(request):
    return render(request, 'homepage/about.html')

def services(request):
    return render(request, 'homepage/services.html')

def contact(request):
    if request.method == 'GET':
        form = ContactForm()
    else:
        form = ContactForm(request.POST)
        if form.is_valid():
            subject = form.cleaned_data['subject']
            name = form.cleaned_data['name']
            from_email = form.cleaned_data['from_email']
            phone_number = form.cleaned_data['phone_number']
            message_raw = form.cleaned_data['message']
            message = name + 'sent the following message of inquiry,' + '\n\n' + message_raw
            try:
                send_mail(subject, message, from_email, ['admin@example.com'])
            except BadHeaderError:
                return HttpResponse('Invalid Header Found.')
            # return redirect("homepage:index") # put in the page to goto after succesful submission over here.
            return redirect("homepage:message_sent")

    return render(request, 'homepage/contact.html', {'form': form})

se_consultants/projects/views.py
# from django.shortcuts import render
from django.views import generic

from .models import Projects

# Create your views here.
class IndexView(generic.ListView):
    template_name = 'projects/index.html'
    context_object_name = 'all_projects'

    def get_queryset(self):
        return Projects.objects.all()

class DetailView(generic.DetailView):
    model = Projects
    template_name = 'projects/details.html'

se_consultants/homepage/templates/homepage/about.html
{% extends "base.html" %} {% load static %} {% block page_content %}

<!-- Everything will go in here now! -->
<link rel="stylesheet" type="text/css" href="{% static 'homepage/about/styles.css' %}">
<title>Synergy Engineering Consultants | About Us</title>
<!-- Shift the image url to the css file -->

<header class="parallax">
    <div class="overlay"></div>
    <div class="container-a">
        <div class="description ">
            <h1>
                Synergy Engineering Consultants
                <!-- <p>About Us</p> -->
                <!-- <button class="btn btn-outline-secondary btn-lg">See more</button> -->
            </h1>
        </div>
    </div>
</header>
<br>
<section class="about" id="about">
    <div class="content-box">
        <h2 class="heading">About Us</h2>
        <p class="text">Synergy Engineering Consultancy has been founded on the principle of providing Electrical Consultancy of the highest order to its clients. This company has been founded by Engr. Muhammad Idris Khan. A veteran in the field of Electrical Engineering
            with an experience spanning more than 35 years of excellent service at K-Electric (formerly Karachi Electric Supply Corporation).
        </p>
    </div>
    <div class="img-box">
        <video src="{% static 'homepage/about/images/about-tile.mp4' %}" muted loop autoplay></video>
    </div>
</section>
<br>
<br>
<section class="about" id="about">
    <div class="img-box-d" id="img-d">
        <img src="{% static 'homepage/about/images/profile_pic.png' %}">
    </div>
    <div class="cont-d" id="contd">
        <h2 class="heading" style="font-size: 20px; align-items: center;">Engr. Muhammad Idris Khan</h2>
        <p class="text">Accomplished professional with over 35 years of experience in independently managing the affairs of key departments at K-Electric. Having lead top tier management roles as HOD and Deputy Director/HOD through the tenure at K-Electric.</p>
    </div>
</section>

<script src="{% static 'homepage/about/script.js' %}" async defer></script>

{% endblock %}

se_consultants/homepage/templates/homepage/contact.html
{% extends "base.html" %} {% load static %} {% block page_content %}
<!-- <h1>Contact Us</h1>
<form method="post">
    {% csrf_token %} {{ form }}
    <div class="form-actions">
        <button type="submit">Send</button>
    </div>
</form> -->
<!doctype html>
<html lang="en">

<head>
    <title>Synergy Engineering Consultants | Contact Us</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href='https://fonts.googleapis.com/css?family=Roboto:400,100,300,700' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'homepage/contact/styles.css' %}">
</head>

<body>
    <section class="ftco-section">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-6 text-center mb-5">
                    <h2 class="heading-section">Contact Us</h2>
                </div>
            </div>
            <div class="row justify-content-center">
                <div class="col-lg-10 col-md-12">
                    <div class="wrapper">
                        <div class="row justify-content-center">
                            <div class="col-lg-8 mb-5">
                                <div class="row">
                                    <div class="col-md-4">
                                        <div class="dbox w-100 text-center">
                                            <div class="icon d-flex align-items-center justify-content-center">
                                                <span class="fa fa-map-marker"></span>
                                            </div>
                                            <div class="text">
                                                <p><span>Address:</span> 92-C Block-6 P.E.C.H.S, Karachi, Pakistan</p>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="dbox w-100 text-center">
                                            <div class="icon d-flex align-items-center justify-content-center">
                                                <span class="fa fa-phone"></span>
                                            </div>
                                            <div class="text">
                                                <p><span>Phone:</span>+92 300 9277467</p>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="dbox w-100 text-center">
                                            <div class="icon d-flex align-items-center justify-content-center">
                                                <span class="fa fa-paper-plane"></span>
                                            </div>
                                            <div class="text">
                                                <!-- <p><span>Email:</span> <a href="synergy.consultants@hotmail.com"><span class="__cf_email__" data-cfemail="a3cacdc5cce3daccd6d1d0cad7c68dc0ccce">[email&#160;protected]</span></a></p> -->
                                                <p><span>Email:</span><a href="synergy.consultants@hotmail.com">synergy.consultants@hotmail.com</a></p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-8">
                                <div class="contact-wrap">
                                    <h3 class="mb-4 text-center">Get in touch with us</h3>
                                    <div id="form-message-warning" class="mb-4 w-100 text-center"></div>
                                    <div id="form-message-success" class="mb-4 w-100 text-center">
                                        Your message was sent, thank you!
                                    </div>
                                    <form method="POST" id="contactForm" name="contactForm" class="contactForm">
                                        {% csrf_token %}
                                        <div class="row">
                                            <div class="col-md-12">
                                                <div class="form-group">

                                                    <!-- <input type="text" class="form-control" name="name" id="name" placeholder="Name"> -->
                                                    {{ form.name.errors }}
                                                    <label for="{{ form.name.id_for_label }}">Your Name</label> {{ form.name }}

                                                </div>
                                            </div>
                                            <div class="col-md-12">
                                                <div class="form-group">
                                                    <!-- <input type="email" class="form-control" name="email" id="email" placeholder="Email"> -->
                                                    {{ form.from_email.errors }}
                                                    <label for="{{ form.from_email.id_for_label }}">Your Email</label> {{ form.from_email }}

                                                </div>
                                            </div>
                                            <div class="col-md-12">
                                                <div class="form-group">
                                                    <!-- <input type="text" class="form-control" name="subject" id="subject" placeholder="Subject"> -->
                                                    {{ form.phone_number.errors }}
                                                    <label for="{{ form.phone_number.id_for_label }}">Phone Number</label> {{ form.phone_number }}

                                                </div>
                                            </div>
                                            <div class="col-md-12">
                                                <div class="form-group">
                                                    <!-- <textarea name="message" class="form-control" id="message" cols="30" rows="8" placeholder="Message"></textarea> -->
                                                    {{ form.subject.errors }}
                                                    <label for="{{ form.subject.id_for_label }}">Subject</label> {{ form.subject }}

                                                </div>
                                            </div>
                                            <div class="col-md-12">
                                                <div class="form-group">
                                                    <!-- <textarea name="message" class="form-control" id="message" cols="30" rows="8" placeholder="Message"></textarea> -->
                                                    {{ form.message.errors }}
                                                    <label id="message" for="{{ form.message.id_for_label }}">Your Message</label> {{ form.message }}

                                                </div>
                                            </div>
                                            <div class="col-md-12">
                                                <div class="form-group">
                                                    <input type="submit" value="Send Message" class="btn btn-primary">
                                                    <div class="submitting"></div>
                                                </div>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
    <!-- <script src="{% static 'homepage/contact/script.js' %}"></script> -->

</body>

</html>
{% endblock %}

se_consultants/homepage/templates/homepage/index.html
{% load static %}
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Synergy Engineering Consultants | Home</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'homepage/styles.css' %}">
</head>

<body>
    <section class="showcase">
        <header>
            <!-- <h2 class="logo">Synergy Engineering</h2> -->
            <img src="{% static 'assets/logo1.png' %}">
            <div class="toggle"></div>
        </header>
        <video src="{% static 'assets/homebg.mkv' %}" muted loop autoplay></video>
        <div class="overlay"></div>
        <div class="text">
            <h2>Synergy Engineering Consultants</h2>
            <h3>Premier consultants in Electrical Engineering</h3>
            <p>With extensive 35 years experience in the field.</p>
            <a href="{% url 'homepage:about' %}">About Us</a>
            <a href="{% url 'homepage:services' %}">Services</a>
            <!-- Replace with projects in the future. -->
        </div>
    </section>
    <div class="menu">
        <ul>
            <li><a href="#">Home</a></li>
            <li><a href="{% url 'homepage:services' %}">Services</a></li>
            <li><a href="{% url 'projects:index' %}">Projects</a></li>
            <li><a href="{% url 'homepage:about' %}">About Us</a></li>
            <li><a href="{% url 'homepage:contact' %}">Contact</a></li>
        </ul>
    </div>


    <script src="{% static 'homepage/script.js' %}" async defer></script>
</body>

</html>

se_consultants/homepage/templates/homepage/message_sent.html
{% load static %}
<h1>Your message has been sent</h1>
<a href="{% url 'homepage:index' %}">Back Home</a>

se_consultants/homepage/templates/homepage/services.html
{% extends "base.html" %} {% load static %} {% block page_content %}

<!-- Everything will go in here now! -->
<link rel="stylesheet" type="text/css" href="{% static 'homepage/services/styles.css' %}">
<title>Synergy Engineering Consultants | About Us</title>
<!-- Shift the image url to the css file -->

<header class="parallax">
    <div class="overlay"></div>
    <div class="container">
        <div class="description ">
            <h1>
                Synergy Engineering Consultants
            </h1>
            <p>We offer complete services in the following domains..</p>
        </div>
    </div>
</header>
<br>
<section class="about" id="about">
    <div class="content-box">
        <h2 class="heading">Electrical Load Assessment</h2>
        <p class="text">For High rises, Commercial/Residential buildings, Housing Societies, Industries, Museums, Libraries and all other types of commercial buildings/</p>
    </div>
    <div class="img-box">
        <img src="{% static 'homepage/services/images/service1.jpg' %}"></img>
    </div>
</section>
<br>
<br>
<section class="about" id="about">
    <div class="img-box">
        <img src="{% static 'homepage/services/images/service2.jpg' %}"></img>
    </div>
    <div class="content-box-right">
        <h2 class="heading">Design & development of Electrical Distribution Network</h2>
        <p class="text">Distribution networks spend heavily on investments and generation. It is only sensible that this power be used as efficiently as possible. We play our role in optimizing the efficiency and capital of our clients.</p>
    </div>
</section>
<br>
<br>
<section class="about" id="about">
    <div class="content-box">
        <h2 class="heading">Energy Audit for efficient use of Electrical Energy </h2>
        <p class="text">Energy Audit helps identify and consequently eliminate energy losses while also enhancing safety and efficiency of electrical equipment.</p>
        <br>
        <ul class="list-unstyled">
            <li class="text">This service includes, </li>
            <li class="text">Preliminary Energy Audit</li>
            <li class="text">General Energy Audit</li>
            <li class="text">Detailed Energy Audit</li>
        </ul>
    </div>
    <div class="img-box">
        <img src="{% static 'homepage/services/images/service3.jpg' %}"></img>
    </div>
</section>
<br>
<br>
<section class="about" id="about">
    <div class="img-box">
        <img src="{% static 'homepage/services/images/service4.jpg' %}"></img>
    </div>
    <div class="content-box-right">
        <h2 class="heading">Power Factor Improvement</h2>
        <p class="text">Improving power factor means reducing the phase difference between voltage and current. This helps in reducing demand charges, improved voltage, reduce power losses as well as increased load carrying capacity in existing infrastructure.</p>
    </div>
</section>
<br>
<br>
<section class="about" id="about">
    <div class="content-box">
        <h2 class="heading">Installation of Solar, Wind & Hybrid Energy Systems</h2>
        <p class="text">Tailor-made alternate energy systems to meet any client's energy requirements.</p>
    </div>
    <div class="img-box">
        <img src="{% static 'homepage/services/images/service5.jpg' %}"></img>
    </div>
</section>
<br>
<br>

<script src="{% static 'homepage/services/script.js' %}" async defer></script>

{% endblock %}

se_consultants/projects/templates/projects/details.html
{% extends "base.html" %} {% load static %} {% block page_content %}
<link rel="stylesheet" type="text/css" href="{% static 'details/styles.css' %}">
<title>Synergy Engineering Consultants | {{ projects.project_name }}</title>
<header class="parallax" style="background-image: url('{% static projects.project_banner %}');">
    <div class="overlay"></div>
    <div class="container">
        <div class="description ">
            <h1>
                Synergy Engineering Consultants
                <!-- <p>{{ product.product_description }}</p> -->
                <!-- <button class="btn btn-outline-secondary btn-lg">See more</button> -->
            </h1>
        </div>
    </div>
</header>

<!-- About the product -->
<div class="about" id="about">
    <div class="container">
        <h1 class="text-center">Details for {{ projects.project_name }}</h1>
        <div class="row">
            <!-- <div class="col-lg-4 col-md-4 col-sm-12">
                <img src="{% static projects.project_banner %}" class="img-fluid">
                <span class="text-center"></span>
            </div> -->
            <div class="col-lg-8 col-md-8 col-sm-12 desc">
                <!-- <h3></h3> -->
                <p>Client Name: {{ projects.client }}</p>
                <p>Service: {{ projects.work_type }}</p>
                <p>Completion Status: {{ projects.completion_status }}</p>
                <!-- <h3>Brief Description:</h3>
                <p>
                    {{ projects.project_description }}
                </p> -->
            </div>
        </div>
    </div>
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="{% static 'details/script.js' %}"></script>
{% endblock %}

se_consultants/projects/templates/projects/index.html
{% extends "base.html" %} {% load static %} {% block page_content %}
<link rel="stylesheet" type="text/css" href="{% static 'index/styles.css' %}">

<title>Synergy Engineering Consultants | Projects</title>
<div class="banner">
    <img src="{% static 'images/projects_cover.jpg' %}">
    <div class="content">
        <h2>Our Projects</h2>
        <p>Following are the projects we completed in our professional capacity</p>
    </div>
</div>
<br>
<br> {% if all_projects %}
<div class="row">
    {% for project in all_projects %}
    <!-- NOW GET A CARD FOR HERE -->
    <div class="card hover">
        <!-- The fucking mistake was here!!! -->
        <a class="hover" href="{% url 'projects:details' project.id %}">
            <div class="card-img" style="background-image: url('{% static project.project_banner %}');">
                <div class="overlay">
                    <div class="overlay-content">
                        <!-- <a class="hover" href="#!">View Product</a> -->
                        <!-- <p class="text">How's this?</p> -->
                    </div>
                </div>
            </div>
        </a>

        <div class="card-content">
            <a href="{% url 'projects:details' project.id %}">
                <h2>{{ project.project_name }}</h2>
                <p>{{ project.client }}</p>
                <p>{{ project.completion_status }}</p>
            </a>
        </div>
    </div>
    {% endfor %}
</div>
{% else %}
<p>No projects to display at the moment..</p>
{% endif %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="{% static 'index/script.js' %}"></script>

{% endblock %}


<!-- Extra code --- Dekh kr delete krdena, -->

se_consultants/se_consultants/templates/base.html
{% load static %}

<body class="hero-anime">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'base/style.css' %}">

    <div class="navigation-wrap bg-dark start-header start-style">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <nav class="navbar navbar-expand-md navbar-dark">
                        <a class="navbar-brand" href="{% url 'homepage:index' %}" target="_blank"><img src="{% static 'base/images/logo1.png' %}" alt="LOGO"></a>
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle Navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                        <div class="collapse navbar-collapse" id="navbarSupportedContent">
                            <ul class="navbar-nav ml-auto py-4 py-md-0">
                                <li class="nav-item pl-4 pl-md-0 ml-0 ml-md-4 active">
                                    <a class="nav-link" href="{% url 'homepage:index' %}">Home</a>
                                </li>
                                <li class="nav-item pl-4 pl-md-0 ml-0 ml-md-4 active">
                                    <a class="nav-link" href="{% url 'homepage:about' %}">About Us</a>
                                </li>
                                <li class="nav-item pl-4 pl-md-0 ml-0 ml-md-4 active">
                                    <a class="nav-link" href="{% url 'homepage:services' %}">Services</a>
                                </li>
                                <li class="nav-item pl-4 pl-md-0 ml-0 ml-md-4 active">
                                    <a class="nav-link" href="{% url 'projects:index' %}">Projects</a>
                                </li>
                                <li class="nav-item pl-4 pl-md-0 ml-0 ml-md-4 active">
                                    <a class="nav-link" href="{% url 'homepage:contact' %}">Contact</a>
                                </li>
                            </ul>
                        </div>
                    </nav>
                </div>
            </div>
        </div>
    </div>
    <div class="my-5 py-5">
    </div>


    <div class="container">
        {% block page_content %}{% endblock %}
    </div>
    <br>
    <br>
    <br>
    <footer class="mainfooter" role="contentinfo">
        <div class="footer-middle">
            <div class="container">
                <div class="row">
                    <div class="col-md-3 col-sm-6">
                        <!-- Column 1 -->
                        <div class="footer-pad">
                            <h4>Contact Us</h4>
                            <ul class="list-unstyled">
                                <li>
                                    <p><span>Address:</span> 92-C Block-6 P.E.C.H.S, Karachi, Pakistan</p>
                                    <!-- <a href="#"></a> -->
                                </li>
                                <li>
                                    <p><span>Phone:</span>+92 300 9277467</p>
                                    <!-- <a href="#"></a> -->
                                </li>
                                <li>
                                    <p><span>Email:</span><a href="synergy.consultants@hotmail.com">synergy.consultants@hotmail.com</a></p>
                                    <!-- <a href="#"></a> -->
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-md-3 col-sm-6">
                        <!-- Blank space -->
                    </div>
                    <div class="col-md-3 col-sm-6">
                        <!-- Column2 -->
                        <div class="footer-pad">
                            <h4>Links</h4>
                            <ul class="list-unstyled">
                                <li><a href="{% url 'homepage:index' %}">Home</a></li>
                                <li><a href="{% url 'homepage:about' %}">About Us</a></li>
                                <li><a href="{% url 'homepage:services' %}">Services</a></li>
                                <li><a href="{% url 'projects:index' %}">Projects</a></li>
                                <li><a href="{% url 'homepage:contact' %}">Contact</a></li>
                            </ul>
                        </div>
                    </div>

                    <div class="col-md-3">
                        <h4>Follow Us</h4>
                        <ul class="social-network social-circle">
                            <!-- <li><a href="#" class="icoFacebook" title="Facebook"><i class="fa fa-facebook"></i></a></li> -->
                            <li><a href="https://pk.linkedin.com/in/muhammad-idris-khan-38a133142" class="icoLinkedin" title="Linkedin"><i class="fa fa-linkedin"></i></a></li>
                        </ul>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12 copy">
                        <p class="text-center">Synergy Engineering Consultants. All rights reserved.</p>
                        <p class="text-center">&copy; Copyright 2021 - Developed by <a href="#!">Next Horizon</a></p>
                    </div>
                </div>
            </div>
        </div>
    </footer>


    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>

    <script src="{% static 'base/script.js' %}"></script>
</body>